### ISSUE TITLE
JellyCram roadmap

### ISSUE THREAD

**Issue by Jerboa-app** [JerboaBurrow/JellyCram#1]
- [x] Tetronimo Meshes
- [x] stable-ish params
- [x] deletion of matching pieces?
- [ ] move active piece (no rotation)
- [ ] if a piece goes above y=1 = game over
- [ ] credits
- [ ] welcome screen
- [ ] settings menu (tetronimo colour maps)
- [ ] sound?
- [ ] better name
- [ ] "fill" mode
- [ ] "classic mode" (i.e. tetris)
